FROM mcr.microsoft.com/dotnet/sdk:5.0.403-alpine3.13 as builder

# This dockerfile takes the Musl build of dotnet library test, and append a custom test runner to run the test DLLs

# Copy the runner project to /runner in the builder
COPY runner /runner
RUN cd /runner && dotnet build -c Release /p:RuntimeOS=linux-musl /p:OutputRid=linux-musl-x64

# This image is built from Dockerfile.musl
FROM hullcritical/dotnet-library-test:release-musl

COPY --from=builder /runner /runner
COPY ./testcases/pass.* /testcases/
COPY ./testcases/fail.txt /testcases/
COPY ./testcases/skip.txt /testcases/

# Remove directories that are not needed for the test run
RUN rm -rf /dotnet-lib-release/testhost
RUN rm -rf /dotnet-lib-release/coreclr
RUN rm -rf /dotnet-lib-release/externals
RUN rm -rf /dotnet-lib-release/docs
RUN rm -rf /dotnet-lib-release/microsoft.netcore.app.runtime.linux-musl-x64
