variables:
  - group: myst-pipeline
  - name: SCRIPTS_ROOT
    value: $(Build.SourcesDirectory)/.azure_pipelines/scripts

parameters:
- name: VERSION
  displayName: VERSION
  type: string
  default: 0.0.0
- name: RELEASE_ARTIFACT
  displayName: RELEASE_ARTIFACT
  type: number
  default: 0
  values:
  - 0
  - 1

trigger: none
pr: none

jobs:
  - job: ReleaseAndTest
    displayName: 'Building Release and Testing'
    timeoutInMinutes: 300
    pool: '1804DC4CCagentpool'
    workspace:
      clean: all

    steps:
      # perform cleanup before starting pipeline
      - script: |
          sudo rm -rf /tmp/myst*
        displayName: 'cleanup tmpfiles'

      # install minimum required package to run pipeline
      - script: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install build-essential python3-setuptools libmbedtls-dev docker-ce -y 
          sudo chmod 666 /var/run/docker.sock
          sudo apt install python3-pip -y
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          docker system prune -a -f
          df
        displayName: 'minimum init config'

      # generate tarball for release binary and source code
      - script: |
          set -ex
          VERSION=${{ parameters.VERSION }}
          echo $VERSION > VERSION
          echo "Creating release version $VERSION"
          
          # remove all untracked files and directories in the git repository
          sudo rm -rf `git ls-files --others --directory`
          make distclean
          touch mystikos-$VERSION.tar.gz
          tar -czf mystikos-$VERSION.tar.gz --exclude=mystikos-$VERSION.tar.gz .
          
          make -j MYST_RELEASE=1 && make bindist
          exit 0
        displayName: 'Generate release v${{ parameters.VERSION }} artifact'
        condition: eq(variables['Agent.JobStatus'], 'succeeded')
        workingDirectory: $(Build.SourcesDirectory)
        env:
          MYST_NIGHTLY_TEST: 1

      # run all tests
      - script: |
          rm -rf mystikos 
          tar -xzf mystikos-${{ parameters.VERSION }}-x86_64.tar.gz
          export PATH="$PATH:$(pwd)/mystikos/bin"
          sed -i 's/BINDIR=$(BUILDDIR)\/bin/BINDIR\=$(TOP)\/mystikos\/bin/g' defs.mak
          sed -i 's/SUBBINDIR=$(BINDIR)\/$(SUBDIR)/SUBBINDIR\=$(BUILDDIR)\/bin\/$(SUBDIR)/g' defs.mak
          make -j tests ALLTESTS=1 VERBOSE=1
        displayName: 'run all tests'
        continueOnError: true
        enabled: true
        workingDirectory: $(Build.SourcesDirectory)
        env:
          MYST_NIGHTLY_TEST: 1

      # run solution tests
      - script: |
          export PATH="$PATH:$(pwd)/mystikos/bin"
          make tests -C $(Build.SourcesDirectory)/solutions
        displayName: 'run solution tests'
        continueOnError: true
        enabled: true
        workingDirectory: $(Build.SourcesDirectory)
        env:
          # by default sql solution test will run on US EAST DB Node
          DB_NAME: $(DB_NAME_USEAST)
          DB_SERVER_NAME: $(DB_SERVER_NAME_USEAST)
          MAA_URL: $(DB_MAA_URL_USEAST)

      - template: step-sql-soln-cacentral.yml
      
      - template: step-azure-sdk-tests.yml

      # if any previous step(s) not succeed, fail the job
      - script: |
          echo "Not all steps succeed."
          exit 1
        displayName: 'Error(s) Check'
        condition: not(eq(variables['Agent.JobStatus'], 'succeeded'))
      
      # publish as artifacts
      - publish: $(System.DefaultWorkingDirectory)/mystikos-${{ parameters.VERSION }}-x86_64.tar.gz
        artifact: 'Release binary'
        displayName: 'Publish release binary'
        condition: and(eq(variables['Agent.JobStatus'], 'succeeded'), eq(variables['RELEASE_ARTIFACT'], '1'))

      - publish: $(System.DefaultWorkingDirectory)/mystikos-${{ parameters.VERSION }}.tar.gz
        artifact: 'Release binary code tarball'
        displayName: 'Publish release source code'
        condition: and(eq(variables['Agent.JobStatus'], 'succeeded'), eq(variables['RELEASE_ARTIFACT'], '1'))
