MYST_DEBUG=1
MYST_PREFIX=/opt/mystikos
#MYST_ENABLE_GCOV=1
#MYST_ENABLE_LEAK_CHECKER=1
MYST_ENABLE_HOSTFS=1
MYST_ENABLE_EXT2FS=1
# openssl or mbedtls
MYST_OE_CRYPTO=openssl_3
#export MYST_MEMCHECK=1
#export MYST_RELEASE=1
export MYST_ENABLE_ZERO_BASE_ENCLAVES=1
