SUBDIR = tests
TOP=$(abspath ..)
include $(TOP)/defs.mak

DIRS =
DIRS += buf
DIRS += paths
DIRS += cpuid
DIRS += argv
DIRS += shlib
DIRS += getcwd
DIRS += rdtsc
DIRS += run
DIRS += echo
DIRS += lthread
DIRS += wake
DIRS += mman
DIRS += fs
DIRS += mount
DIRS += cpio
DIRS += elf
DIRS += strings
DIRS += empty
DIRS += getpid
DIRS += json
DIRS += conf
DIRS += nbio

include $(TOP)/rules.mak
