FROM mcr.microsoft.com/dotnet/sdk:5.0.403-focal as builder

# This dockerfile takes the Musl build of dotnet library test, and append a custom test runner to run the test DLLs

# Copy the runner project to /runner in the builder
COPY runner /runner
RUN cd /runner && dotnet build -c Release

FROM hullcritical/dotnet-library-test:release-glibc

COPY --from=builder /runner /runner
COPY ./testcases/pass.txt /testcases/
COPY ./testcases/fail.txt /testcases/
COPY ./testcases/skip.txt /testcases/
