# Base image recommendation from dotnet git repo - https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/linux-instructions.md#docker-images
FROM mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-a50a721-20191120200116 as builder
ARG TAG=v5.0.11

WORKDIR /app
RUN git clone --depth 1 --single-branch --recurse-submodules --branch ${TAG} https://github.com/dotnet/aspnetcore
WORKDIR /app/aspnetcore
RUN ./build.sh -nobl -c Debug \
    --arch x64 --all \
	--no-build-nodejs --no-build-java; \
	exit 0 # ignore build errors

FROM mcr.microsoft.com/dotnet/runtime:5.0-focal

WORKDIR /aspnetcore
COPY --from=builder /app/aspnetcore/.dotnet .dotnet
COPY --from=builder /app/aspnetcore/artifacts/bin artifacts/bin/
