#!/bin/bash

ROOT=../../../../../3rdparty/libc/libc-test/src

FILES=`ls ${ROOT}/functional/*.c`

for i in ${FILES}
do
    SOURCE=`basename ${i}`
    MAIN=`echo ${SOURCE} | sed 's/\.c//g' | sed 's/-/_/g'`_main
cat > ${SOURCE} <<EOF
#include "test.h"
#include <unistd.h>
#define main ${MAIN}
#include "${ROOT}/functional/${SOURCE}"
EOF
done

FILENAME=functional.c

rm -f ${FILENAME}

cat >> ${FILENAME} <<EOF
#include "test.h"

void test_functional(void)
{
EOF

for i in ${FILES}
do
    SOURCE=`basename ${i}`
    MAIN=`echo ${SOURCE} | sed 's/\.c//g' | sed 's/-/_/g'`_main
cat >> ${FILENAME} <<EOF
    extern int ${MAIN}(void);
    t_status = 0;
    printf("=== running ${MAIN}\n");
    OE_TEST(${MAIN}() == 0);

EOF
done

cat >> ${FILENAME} <<EOF
}
EOF
