#!/bin/bash

##==============================================================================
##
## check-format
##
## Synopsis:
##     Detect misformatted source code files in the repository and exit with
##     1 if any are found. Else exit with 0.
##
## Usage:
##     check-format
##
##==============================================================================

# process options:
for opt
do

  arg=`expr "x$opt" : 'x[^=]*=\(.*\)'`
  case $opt in

    --staged)
      staged=1
      shift
      ;;

    --*)
      echo "$0: unknown option:  $opt"
      exit 1
      ;;

  esac

done

if [ "${staged}" == "1" ]; then
    opts=--staged
fi

./scripts/code-format --check $(./scripts/sources ${opts})
