#!/bin/bash

##==============================================================================
##
## Usage:
##     docker-build-ext2 <docker_file> <ext2_image>
##
## Build a docker image and write the output to an EXT2 image
##
##==============================================================================

##
## Check usage
##
if [ "$#" != "2" ]; then
    echo "Usage: $0 <docker_file> <ext2_image>"
    exit 1
fi

##
## Gather command-line arguments
##
docker_file=$1
ext2_image=$2

##
## Check for existence of docker file
##
if [ ! -f "${docker_file}" ]; then
    echo "$0: docker file not found: ${docker_file}"
    exit 1
fi

##
## Create a temporary mount directory
##
mnt_dir=$(/bin/mktemp -d)
if [ ! -d ${mnt_dir} ]; then
    echo "$0: failed to create temporary mount directory"
    exit 1
fi

##
## Create a temporary iid file
##
iid_file=$(/bin/mktemp)
if [ ! -f ${iid_file} ]; then
    echo "$0: failed to create temporary iid file"
    exit 1
fi

##
## Locate the binary directory (where myst programs reside)
##
bindir=$(realpath $(dirname $0)/../build/bin)
if [ ! -d "${bindir}" ]; then
    echo "$0: bin directory not found: ${bindir}"
    exit 1
fi


##
## Build the docker image
##
docker build --quiet --iidfile ${iid_file} -f ${docker_file} .
if [ "$?" != "0" ]; then
    echo "$0: failed to build the docker image"
    exit 1
fi

##
## check for existence of the mount-docker-image program
##
mount_docker_image=${bindir}/mount-docker-image
if [ ! -x "${mount_docker_image}" ]; then
    echo "$0: cannot find mount-docker-image program"
    exit 1
fi

##
## check for existence of the myst program
##
myst=${bindir}/myst
if [ ! -x "${myst}" ]; then
    echo "$0: cannot find myst program"
    exit 1
fi

##
## mount the docker image
##
${mount_docker_image} ${iid_file} ${mnt_dir} | xargs sudo
if [ "$?" != "0" ]; then
    echo "$0: mount-docker-image program failed"
    exit 1
fi

##
## convert the mounted docker image into an EXT2 image
##
sudo ${myst} mkext2 --force ${mnt_dir} ${ext2_image}
if [ "$?" != "0" ]; then
    echo "$0: myst mkext2 command failed"
    exit 1
fi

##
## umount the docker image and remove temporary files:
##
sudo umount ${mnt_dir}
rm -rf ${mnt_dir}
rm -rf ${iid_file}
