#!/bin/bash

if [ ! -d ./third_party ]; then
    echo "$0: please run from the root of the source tree"
    exit 1
fi

##==============================================================================
##
## Make a list of project directories (exclude build and third_party)
##
##==============================================================================

dirs=$(ls -d -1 */ | grep -v third_party | grep -v build )

##==============================================================================
##
## Make a list of all source files:
##
##==============================================================================

for i in ${dirs}
do
    src+="$(find $i -name '*.[ch]') "
    src+="$(find $i -name '*.s') "
done

##==============================================================================
##
## Make a list of all Makefiles
##
##==============================================================================

for i in ${dirs}
do
    mak+="$(find $i -name '*.mak') "
    mak+="$(find $i -name 'Makefile') "
    mak+="$(find $i -name 'Makefile') "
    mak+="config.mak "
    mak+="defs.mak "
    mak+="rules.mak "
    mak+="Makefile "
done

##==============================================================================
##
## Make a list of .md files
##
##==============================================================================

for i in ${dirs}
do
    md+="$(find $i -name '*.md') "
done

md+="./README.md"

##==============================================================================
##
## Make a list of .edl files
##
##==============================================================================

for i in ${dirs}
do
    edl+="$(find $i -name '*.edl') "
done

##==============================================================================
##
## Make a list of .json files
##
##==============================================================================

for i in ${dirs}
do
    json+="$(find $i -name '*.json') "
done

##==============================================================================
##
## Make a list of all scripts
##
##==============================================================================

scripts+="$(find ./scripts/* | grep -v libos2myst) "
scripts+="./tests/libc/run-libc-test "

##==============================================================================
##
## Make a list of miscellaneous files
##
##==============================================================================

misc+="./tests/libc/run-libc-test "
misc+="./.azure_pipelines/ci-pipeline-makefile.yml "
misc+="./doc/todo.txt "
misc+="./.gitignore "
misc+="./solutions/dotnet/config.json "
misc+="./third_party/openenclave/Makefile "
misc+="./.azure_pipelines/ci-pipeline-makefile-nightly.yml "
misc+="./.azure_pipelines/ci-pipeline-code-coverage-nightly.yml "
misc+="./samples/docker/helloworld/Dockerfile "
misc+="./docker/build-libos/Dockerfile "
misc+="./docker/build-libos/build-libos.sh "
misc+="./third_party/musl/crt/patch2.diff "
misc+="./tests/libos/exec-signed-2/expected "
misc+="./tests/libos/exec-package/expected-no-args "
misc+="./tests/libos/exec-package/expected-args "
misc+="./tests/libos/exec-package/expected "
misc+="./tests/libos/exec-signed-1/expected "
misc+="./solutions/dotnet/HelloWorld/Program.cs "
misc+="./third_party/LICENSES.md "
misc+="./third_party/musl/crt/Makefile "

##==============================================================================
##
## Apply SED substitutions
##
##==============================================================================

for i in ${src} ${mak} ${md} ${edl} ${json} ${scripts} ${misc}
do
    echo "Converting ${i}..."
    tmpfile=$i.subbak
    cp $i ${tmpfile}
    sed -f ./scripts/libos2myst.sed ${tmpfile} > $i
    rm -f ${tmpfile}
done

##==============================================================================
##
## Rename files:
##
##==============================================================================

git mv ./tools/libos/libos.edl ./tools/libos/myst.edl
git mv ./docker/build-libos/build-libos.sh ./docker/build-libos/build-myst.sh
git mv ./doc/open-libos-components.png ./doc/mystikos-components.png
git mv ./scripts/libos_cc ./scripts/myst_cc
git mv ./docker/build-libos ./docker/build-myst
git mv ./tests/libos ./tests/myst
git mv ./include/libos ./include/myst
git mv ./tools/libos ./tools/myst
