#!/bin/bash

# This script generates the code coverage data for myst project. 
# You must run tests with MYST_ENABLE_GCOV=1 to populate the required files
# This script does these steps:
# 1. Creates lcov folder under project root folder
# 2. Copies crt, kernel, tools *.gcno and *.gcda files to the same location as their *.c and *.h files
# 3. Copies *.c and *.h source files as needed (only ones whos location is redefined in their Makefile)
# 4. Generates lcov.info from all the files into the $MYST_ROOT folder
# 5. From info files it generates html code coverage report into ROOT/lcov

MYST_ROOT="$(realpath "$(dirname "$0")/..")"

cp -r "${MYST_ROOT}"/build/obj/tools/* -t "${MYST_ROOT}"/tools
cp -r "${MYST_ROOT}"/build/obj/kernel/* -t "${MYST_ROOT}"/kernel
cp -r "${MYST_ROOT}"/build/obj/crt/"${MYST_ROOT}"/third_party/* -t "${MYST_ROOT}"/third_party
cp "${MYST_ROOT}"/build/obj/crt/*.gc* -t "${MYST_ROOT}"/crt
cp "${MYST_ROOT}"/tools/myst/config.c "${MYST_ROOT}"/tools/myst/config_file.c -t "${MYST_ROOT}"/tools
cp "${MYST_ROOT}"/tools/myst/common.c "${MYST_ROOT}"/tools/myst/kargs.c -t "${MYST_ROOT}"/tools

rm $(find "${MYST_ROOT}"/build/obj/ -name "*.gc*")

lcov -c -d . -o "${MYST_ROOT}"/lcov.info

rm -rf "${MYST_ROOT}"/lcov
mkdir "${MYST_ROOT}"/lcov
genhtml -o "${MYST_ROOT}"/lcov "${MYST_ROOT}"/lcov.info
