#!/bin/bash

# This script generates the code coverage data for myst project. 
# You must run tests with MYST_ENABLE_GCOV=1 to populate the required files
# This script does these steps:
# 1. Creates lcov folder under project root folder
# 2. Copies crt, kernel, tools *.gcno and *.gcda files to the same location as their *.c and *.h files
# 3. Copies *.c and *.h source files as needed (only ones whos location is redefined in their Makefile)
# 4. Generates lcov.info from all the files into the $MYST_ROOT folder
# 5. From info files it generates html code coverage report into ROOT/lcov

MYST_ROOT="$(realpath "$(dirname "$0")/..")"

set -x 

cp -r "${MYST_ROOT}"/build/obj/tools/* -t "${MYST_ROOT}"/tools
cp -r "${MYST_ROOT}"/build/obj/utils/* -t "${MYST_ROOT}"/utils
cp -r "${MYST_ROOT}"/build/obj/hostfs/* -t "${MYST_ROOT}"/hostfs
cp -r "${MYST_ROOT}"/build/obj/host/* -t "${MYST_ROOT}"/host
cp -r "${MYST_ROOT}"/build/obj/ext2/* -t "${MYST_ROOT}"/ext2
cp -r "${MYST_ROOT}"/build/obj/kernel/* -t "${MYST_ROOT}"/kernel
cp -r "${MYST_ROOT}"/build/obj/oe/* -t "${MYST_ROOT}"/oe
cp -r "${MYST_ROOT}"/build/obj/json/* -t "${MYST_ROOT}"/json
cp -r "${MYST_ROOT}"/build/obj/target/* -t "${MYST_ROOT}"/target
# cp -r "${MYST_ROOT}"/build/obj/crt/"${MYST_ROOT}"/third_party/* -t "${MYST_ROOT}"/third_party
cp "${MYST_ROOT}"/build/obj/crt/*.gc* -t "${MYST_ROOT}"/crt
cp "${MYST_ROOT}"/tools/myst/config.c "${MYST_ROOT}"/tools/myst/config_file.c -t "${MYST_ROOT}"/tools
cp "${MYST_ROOT}"/tools/myst/common.c "${MYST_ROOT}"/tools/myst/kargs.c -t "${MYST_ROOT}"/tools
cp "${MYST_ROOT}"/tools/myst/options.c -t "${MYST_ROOT}"/tools

rm -rf "${MYST_ROOT}"/../shared
mkdir "${MYST_ROOT}"/../shared
cp "${MYST_ROOT}"/target/shared/crypto.c -t "${MYST_ROOT}"/../shared
cp -r "${MYST_ROOT}"/build/obj/target/shared/crypto.* -t "${MYST_ROOT}"/../shared
touch "${MYST_ROOT}"/target/shared/crypto.gcda
touch "${MYST_ROOT}"/target/shared/crypto.gcno

rm $(find "${MYST_ROOT}"/build/obj/ -name "*.gc*")
rm $(find "${MYST_ROOT}" -wholename "*build*gcno")
rm $(find "${MYST_ROOT}" -wholename "*build*gcda")

# remove the gcda files created in the test directories
rm $(find "${MYST_ROOT}"/tests/ -name "*.gc*")

lcov --rc lcov_branch_coverage=1 -c -d . -o "${MYST_ROOT}"/lcov.info
lcov --list lcov.info

rm -rf "${MYST_ROOT}"/lcov
mkdir "${MYST_ROOT}"/lcov
genhtml --branch-coverage -o "${MYST_ROOT}"/lcov "${MYST_ROOT}"/lcov.info
