#!/bin/bash

# This script generates the code coverage data for myst project. 
# You must run unit tests, libc tests, and samples with MYST_ENABLE_GCOV=1 first
# This script does these steps:
# 1. Creates gcov_pot folder under project root folder
# 2. Copies crt, utils, host, kernel and libc (third_party/enclave-musl/musl) *.gcno files
# 3. Copies *.c and *.h source files
# 4. Finds all generated ramfs/ folders under unit tests, libc tests and solutions
# 5. For each ramfs/ folder it copies *.gcda files into gcov_pot and generates info files 1.info, 2.info, ...
# 6. Generates consolidated total_cov.info from individual info files
# 7. From info files it generates html code coverage report into gcov_pot/myst_cc/
# 8. Generates myst_cc.zip file from gcov_pot/myst_cc/
#
# This script eventualy generates myst_cc.zip which has zipped HTML code coverage report and total_cov.info

MYST_ROOT="$(realpath "$(dirname "$0")/..")"

cp -r "${MYST_ROOT}"/build/obj/tools/ -t "${MYST_ROOT}"/tools
cp -r "${MYST_ROOT}"/build/obj/kernel/ -t "${MYST_ROOT}"/kernel
cp -r "${MYST_ROOT}"/build/obj/crt/"${MYST_ROOT}"/third_party/ -t "${MYST_ROOT}"/third_party
cp "${MYST_ROOT}"/build/obj/crt/*.gc* -t "${MYST_ROOT}"/crt

rm $(find "${MYST_ROOT}"/build/obj/ -name "*.gc*")

lcov -c -d . -o "${MYST_ROOT}"/lcov.info

# change the info file to replace some instances of tools/blah with tools/myst
mkdir "${MYST_ROOT}"/lcov
genhtml -o "${MYST_ROOT}"/lcov "${MYST_ROOT}"/lcov.info

echo "Copied crt,host,kernel,target,tools,utils, gcno & gcda files"

