#!/bin/bash

# Usage of this script from Makefiles:
# TESTNAME and TESTDIR is setup by defs.mak.
#
# TOP is the top-level directory of mystikos repository.
#
# TESTDIR is $(TOP)/build/tests by default. It should be specified explicity if running tests
# from a different directory.
#
# TESTNAME is the relative directory path of the Makefile invoking runtest. Its relative to TOP.
# TESTNAME may additionally have a suffix, which can be specified via TESTSUFFIX.
# This is used by tests/Makefile to differentiate between sgx and linux target runs.
#
# If there are multiple subtests under directory pointed by TESTNAME,
# SUBTEST can be used to differentiate between them. If not specified,
# its computed by "cmd##*/". This treats the command passed to runtest as a path,
# and computes the basepath, i.e the substring after the last "/" in cmd.
#
# For eg:
#
# If pwd is $(HOME)/mystikos/tests/ltp
# And runtest is invoked with:
# $(RUNTEST) $(MYST_EXEC) rootfs /ltp/testcases/kernel/syscalls/bind/bind01
#
# TOP = $(HOME)/mystikos
# TESTDIR = $(HOME)/mystikos/build/tests
# TESTNAME = tests/ltp (assuming no TESTSUFFIX)
# SUBTEST = bind01

if [ "$#" == "0" ]; then
    echo "Usage: $0 <test> <args...>"
    exit 1
fi

if [ -z "${TESTNAME}" ]; then
    echo "$0: TESTNAME is undefined"
    exit 1
fi

if [ -z "${TESTDIR}" ]; then
    echo "$0: TESTDIR is undefined"
    exit 1
fi

TESTSUBDIR=${TESTDIR}/${TESTNAME}

# Use colors if stdout is a tty device (non-batch mode)
green="\e[32m"
red="\e[31m"
lightblue="\e[94m"
magenta="\e[35m"
cyan="\e[36m"
reset="\e[39m"

test_passed()
{
    local cmd=$*
    if [ -z "${SUBTEST}" ]; then
        local subtest=${cmd##*/}
    else
        local subtest="${SUBTEST}"
    fi
    echo -e "${green}    passed (${TESTNAME}/${subtest})${reset}"
    mkdir -p "${TESTSUBDIR}/${subtest}"
    echo "" >> "${TESTSUBDIR}/${subtest}/passed"
}

test_failed()
{
    local cmd=$*
    if [ -z "${SUBTEST}" ]; then
        local subtest=${cmd##*/}
    else
        local subtest="${SUBTEST}"
    fi
    echo -e "${red}    failed (${TESTNAME}/${subtest})${reset}"
    mkdir -p "${TESTSUBDIR}/${subtest}"
    echo "" >> "${TESTSUBDIR}/${subtest}/failed"
}

test_timedout()
{
    local cmd=$*
    if [ -z "${SUBTEST}" ]; then
        local subtest=${cmd##*/}
    else
        local subtest="${SUBTEST}"
    fi
    echo -e "${red}    timedout (${TESTNAME}/${subtest})${reset}"
    mkdir -p "${TESTSUBDIR}/${subtest}"
    echo "" >> "${TESTSUBDIR}/${subtest}/failed"
}

if [ -z "${TIMEOUT}" ]; then
timeout=120
else
timeout=${TIMEOUT}
fi

run_test()
{
    local cmd;

    # Remove extraneous whitespace from the command:
    for i in $*
    do
        cmd="${cmd} $i"
    done

    if [ -z "${SUBTEST}" ]; then
        local subtest=${cmd##*/}
    else
        local subtest="${SUBTEST}"
    fi

    echo -e "${lightblue}=== start (${TESTNAME}/${subtest})${reset}"

    if [ -z "${NOTIMEOUT}" ]; then
        timeout_command="/usr/bin/timeout ${timeout}"
    else
        timeout_command=
    fi

    # write resource statistics in a temporary file
    # %e format specifies we are only interested in elapsed wall clock time(in seconds).
    local tempfile=$(/bin/mktemp)
    time_command="/usr/bin/time -f "%e" --quiet -o ${tempfile}"

    # run the test
    echo "runtest[start]: ${timeout_command} ${time_command} ${cmd}"
    ${timeout_command} ${time_command} ${cmd}
    ret=$?
    echo "runtest[finish]: ${timeout_command} ${time_command} ${cmd}"
    
    seconds=$(cat ${tempfile})
    rm -f ${tempfile}

    # record test run status
    if [ "${ret}" == "0" ]; then
        test_passed $cmd
        echo -e "${lightblue}    ${seconds} seconds${reset}"
    elif [ "${ret}" == "124" ]; then
        test_timedout $cmd
    else
        test_failed ${cmd}
        echo -e "${lightblue}    ${seconds} seconds${reset}"
    fi

    echo ""
}

summarize()
{
    if [ "${SUMMARY}" == "1" ]; then
        find ${TESTDIR} -name 'failed' | wc -l > ${TESTDIR}/num.failed
        find ${TESTDIR} -name 'passed' | wc -l > ${TESTDIR}/num.passed
        num_passed=$(cat ${TESTDIR}/num.passed)
        num_failed=$(cat ${TESTDIR}/num.failed)

        echo -e "${magenta}passed: ${num_passed}${reset}"
        echo -e "${magenta}failed: ${num_failed}${reset}"

        if [ "${num_failed}" != "0" ]; then
            failed=$(find ${TESTDIR} -name failed)
            for i in ${failed}
            do
                r=$(echo ${i} | sed "s~${TESTDIR}/~~g")
                echo -e "${red}failed: ${r}${reset}"
            done
            exit 1
        else
            exit 0
        fi
    fi
}

mkdir -p ${TESTSUBDIR}

if [ ! -d "${TESTSUBDIR}" ]; then
    echo "$0: cannot create directory: ${TESTSUBDIR}"
    exit 1
fi

run_test $*

summarize
