#!/bin/bash

##==============================================================================
##
## sources
##
## Synopsis:
##     Compile a list of sources files (.c, .cpp, and .h) in the git repository.
##     Does not include submodules.
##
## Usage:
##     sources
##
##==============================================================================

commit=0

# process options:
for opt
do

  arg=`expr "x$opt" : 'x[^=]*=\(.*\)'`
  case $opt in

    --commit)
      commit=1
      shift
      ;;

    --*)
      echo "$0: unknown option:  $opt"
      exit 1
      ;;

  esac

done

top=$(git rev-parse --show-toplevel)

cd ${top}

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "${commit}" == "1" ]; then
    # form a list of files to be committed
    files=$(git commit --dry-run --short --untracked-files=no | cut -f3 -d" ")
else
    # form a list of all files in repository
    files=$(git ls-tree -r ${branch} --name-only)
fi

sources=

for i in ${files}
do
    case $i in

        third_party/*)
            # ignore these directories
            ;;

        *.c|*.h|*.cpp)
            sources+="${i} "
            ;;

        *)
            # ignore this file
            ;;
    esac
done

echo ${sources}
